// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful"

export interface IPageFields {
  /** Paginatitel */
  title: string

  /** URL */
  url: string

  /** Afbeelding */
  image?: Asset | undefined

  /** Vrije tekst */
  description?: string | undefined
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "page"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IProductFields {
  /** Naam */
  name: string

  /** URL */
  url: string

  /** Categorie */
  category: "Tafels" | "Buitenmeubels" | "Projecten"

  /** Tonen op homepage */
  homepage: boolean

  /** Opleverdatum */
  deliveryDate: string

  /** Omschrijving */
  description?: string | undefined

  /** Hoofdafbeelding */
  mainImage: Asset

  /** Sfeerbeelden */
  atmosphericImages?: Asset[] | undefined
}

export interface IProduct extends Entry<IProductFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "product"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export type CONTENT_TYPE = "page" | "product"

export type LOCALE_CODE = "nl"

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "nl"
